"""
Text cleaning utilities with configurable regex filters for removing noise from extracted documents.
"""

import re
from typing import Dict, List, Pattern
from dataclasses import dataclass


@dataclass
class CleaningRule:
    """Represents a text cleaning rule with pattern and description."""
    name: str
    pattern: str
    flags: int = 0
    description: str = ""
    enabled: bool = True


class TextCleaner:
    """Advanced text cleaner with configurable regex patterns for removing noise."""
    
    def __init__(self):
        self.rules: Dict[str, CleaningRule] = {}
        self._compile_default_rules()
    
    def _compile_default_rules(self):
        """Initialize with default cleaning rules."""
        default_rules = [
            # Email headers
            CleaningRule(
                name="email_headers",
                pattern=r'^(From|To|Cc|Bcc|Subject|Date|Reply-To|Message-ID|In-Reply-To|References):.*$',
                flags=re.MULTILINE | re.IGNORECASE,
                description="Remove email header lines"
            ),
            
            # Signature separators
            CleaningRule(
                name="signature_separators",
                pattern=r'^\s*(--|__|==)[\s_-]*$',
                flags=re.MULTILINE,
                description="Remove signature separator lines"
            ),
            
            # Common sign-offs
            CleaningRule(
                name="sign_offs",
                pattern=r'^\s*(Sincerely|Best regards|Kind regards|Thanks|Thank you|Cheers|Regards),*\s*$',
                flags=re.MULTILINE | re.IGNORECASE,
                description="Remove common email sign-offs"
            ),
            
            # Phone numbers
            CleaningRule(
                name="phone_numbers",
                pattern=r'\b\+?[1-9]\d{1,14}\b|\b\(\d{3}\)[\s.-]?\d{3}[\s.-]?\d{4}\b',
                description="Remove phone numbers"
            ),
            
            # Email addresses
            CleaningRule(
                name="email_addresses",
                pattern=r'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b',
                description="Remove email addresses"
            ),
            
            # URLs
            CleaningRule(
                name="urls",
                pattern=r'https?://[^\s]+|www\.[^\s]+',
                description="Remove URLs"
            ),
            
            # Social media handles
            CleaningRule(
                name="social_media",
                pattern=r'@[A-Za-z0-9_]+',
                description="Remove social media handles"
            ),
            
            # Disclaimers
            CleaningRule(
                name="disclaimers",
                pattern=r'(Disclaimer|Confidential|This email).*?(?=\n\n|$)',
                flags=re.IGNORECASE | re.DOTALL,
                description="Remove legal disclaimers"
            ),
            
            # Footer boilerplate
            CleaningRule(
                name="footer_boilerplate",
                pattern=r'(Sent from|Powered by|Generated by|Created with).*?(?=\n\n|$)',
                flags=re.IGNORECASE | re.DOTALL,
                description="Remove footer boilerplate text"
            ),
            
            # PDF artifacts
            CleaningRule(
                name="pdf_page_numbers",
                pattern=r'Page\s+\d+\s+of\s+\d+',
                flags=re.IGNORECASE,
                description="Remove page number indicators"
            ),
            
            # Dates and times
            CleaningRule(
                name="dates_times",
                pattern=r'\d+/\d+/\d+|\d+-\d+-\d+|\d+:\d+:\d+',
                description="Remove dates and timestamps"
            ),
            
            # Copyright notices
            CleaningRule(
                name="copyright",
                pattern=r'Copyright.*?(?=\n\n|$)',
                flags=re.IGNORECASE | re.DOTALL,
                description="Remove copyright notices"
            ),
        ]
        
        for rule in default_rules:
            self.add_rule(rule)
    
    def add_rule(self, rule: CleaningRule):
        """Add a new cleaning rule."""
        self.rules[rule.name] = rule
    
    def remove_rule(self, name: str):
        """Remove a cleaning rule by name."""
        self.rules.pop(name, None)
    
    def enable_rule(self, name: str):
        """Enable a cleaning rule."""
        if name in self.rules:
            self.rules[name].enabled = True
    
    def disable_rule(self, name: str):
        """Disable a cleaning rule."""
        if name in self.rules:
            self.rules[name].enabled = False
    
    def get_enabled_rules(self) -> List[CleaningRule]:
        """Get all enabled rules."""
        return [rule for rule in self.rules.values() if rule.enabled]
    
    def clean(self, text: str) -> str:
        """
        Apply all enabled cleaning rules to the text.
        
        Args:
            text: Raw text to clean
            
        Returns:
            Cleaned text
        """
        if not text or not text.strip():
            return ""
        
        # Pre-processing
        text = self._normalize_whitespace(text)
        
        # Apply all enabled rules
        for rule in self.get_enabled_rules():
            compiled_pattern = re.compile(rule.pattern, rule.flags)
            text = compiled_pattern.sub('', text)
        
        # Post-processing
        text = self._final_cleanup(text)
        
        return text.strip()
    
    def _normalize_whitespace(self, text: str) -> str:
        """Normalize whitespace and line endings."""
        # Normalize line endings
        text = text.replace('\r\n', '\n').replace('\r', '\n')
        
        # Replace multiple newlines with double newlines
        text = re.sub(r'\n\s*\n\s*\n+', '\n\n', text)
        
        # Replace multiple spaces with single spaces
        text = re.sub(r' +', ' ', text)
        
        # Strip each line
        lines = [line.strip() for line in text.split('\n')]
        return '\n'.join(lines)
    
    def _final_cleanup(self, text: str) -> str:
        """Final cleanup steps."""
        # Remove zero-width characters
        text = re.sub(r'[\u200B-\u200D\uFEFF]', '', text)
        
        # Normalize quotes and dashes
        text = text.replace('\u2013', '-').replace('\u2014', '-')
        text = text.replace('\u2018', "'").replace('\u2019', "'")
        text = text.replace('\u201C', '"').replace('\u201D', '"')
        
        # Remove excessive punctuation
        text = re.sub(r'([.!?])\1{2,}', r'\1', text)
        
        # Remove standalone special characters or very short lines
        lines = text.split('\n')
        cleaned_lines = []
        for line in lines:
            stripped = line.strip()
            # Keep lines with meaningful content
            if len(stripped) > 2 or (len(stripped) >= 1 and stripped.isalnum()):
                cleaned_lines.append(line)
        
        return '\n'.join(cleaned_lines)


# Global instance for easy access
text_cleaner = TextCleaner()


def clean_document_text(text: str) -> str:
    """
    Convenience function to clean document text using default rules.
    
    Args:
        text: Raw text extracted from document
        
    Returns:
        Cleaned text ready for processing
    """
    return text_cleaner.clean(text)


# Example usage:
if __name__ == "__main__":
    sample_text = """
From: john.doe@company.com
To: jane.smith@client.com
Subject: Project Update
Date: 2024-01-15

Dear Jane,

Here is the project update you requested.

Best regards,
John Doe
Senior Developer
john.doe@company.com
+1 (555) 123-4567
www.company.com

--
This email is confidential. Please do not forward.
"""
    
    cleaned = clean_document_text(sample_text)
    print("Original:")
    print(sample_text)
    print("\nCleaned:")
    print(cleaned)